/** CSS variables supplied by every concrete AwesomeADO theme. */
export const THEME_COLOR_VARIABLES = [
  "--background-color",
  "--callout-background-color",
  "--text-primary-color",
  "--text-secondary-color",
  "--communication-background",
  "--communication-foreground",
  "--text-on-communication-background",
  "--palette-neutral-4",
  "--palette-neutral-8",
  "--palette-neutral-20",
  "--component-menu-separator-color",
  "--bg",
  "--surface",
  "--surface-hover",
  "--text",
  "--text-muted",
  "--border",
  "--accent",
  "--accent-contrast",
  "--warning",
  "--error",
  "--error-background",
  "--status-error-text",
  "--palette-error-text",
  "--palette-error-background",
  "--shadow",
  "--shadow-subtle",
  "--control-border",
  "--control-border-strong",
  "--control-border-emphasis",
  "--control-background-subtle",
  "--control-background-muted",
  "--control-background-hover",
  "--spinner-track",
  "--spinner-head",
  "--eta-overdue",
  "--eta-soon",
  "--eta-upcoming",
  "--eta-distant",
  "--mention-foreground",
  "--mention-themed-foreground",
  "--mention-highlight",
  "--open-command-foreground",
  "--marker-blocked-background",
  "--marker-blocked-foreground",
  "--marker-other-background",
  "--marker-other-foreground",
  "--marker-interrupt-background",
  "--marker-interrupt-foreground",
  "--sprint-past-foreground",
  "--success-foreground",
  "--completion-foreground",
  "--priority-background",
  "--priority-border",
  "--priority-critical-foreground",
  "--priority-high-foreground",
  "--priority-medium-foreground",
  "--status-neutral-background",
  "--status-neutral-border",
  "--status-blue-background",
  "--status-blue-border",
  "--status-yellow-background",
  "--status-yellow-border",
  "--status-green-background",
  "--status-green-border",
  "--status-green-foreground",
  "--status-red-background",
  "--status-red-border",
  "--status-red-foreground",
  "--activity-created-background",
  "--activity-updated-background",
  "--activity-notes-background",
  "--activity-foreground",
  "--note-foreground",
  "--description-neutral-background",
  "--description-neutral-active-background",
  "--type-tint-background",
  "--untagged-background",
  "--tag-foreground",
  "--tag-selected-border",
  "--write-status-border",
  "--write-status-shadow",
  "--popup-shadow-strong",
] as const;

export type ThemeColorVariable = (typeof THEME_COLOR_VARIABLES)[number];
export type ThemeColorScheme = "dark" | "light";
export type ThemeColors = Readonly<Record<ThemeColorVariable, string>>;

/** A complete, independently selectable visual theme. */
export interface ThemeDefinition<Id extends string = string> {
  readonly id: Id;
  readonly label: string;
  readonly colorScheme: ThemeColorScheme;
  readonly colors: ThemeColors;
}
